=== aikitpete/uiclientiphone/src/configuration/schemas/classpathfile.xml.xsd
<?xml version="1.0" encoding="UTF-8"?>


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ClassPaths" type="ClassPathsType">
    </xs:element>

    <xs:complexType name="ClassPathsType">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element type="classType" name="class"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="classType">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element type="propertyType" name="property"/>
        </xs:sequence>
        <xs:attribute name="name" use="required"/>
        <xs:attribute type="xs:string" name="path" use="required"/>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:attribute type="xs:string" name="uiName" use="required"/>
        <xs:attribute type="xs:string" name="asName" use="required"/>
        <xs:attribute type="xs:string" name="defaultValue" use="optional"/>
    </xs:complexType>

</xs:schema>

=== aikitpete/uiclientiphone/out/production/test/configuration/files/uicomponents.xml
<ClassPaths xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../schemas/classpathfile.xml.xsd">
    <class name="public.media.still" path="mx.controls.Image">
        <property uiName="url" asName="load()" defaultValue=""/>
    </class>
    <class name="public.button" path="mx.controls.Button">
        <property uiName="name" asName="label" defaultValue=""/>
    </class>
    <class name="public.input" path="mx.controls.TextArea">

    </class>
    <class name="public.text" path="mx.controls.Label">

    </class>
    <class name="public.checkbox" path="mx.controls.CheckBox">
        <property uiName="name" asName="label" defaultValue=""/>
    </class>
    <class name="public.media.video" path="lib.components.customcomponents.ExtendedVideoDisplay">
        <property uiName="url" asName="source" defaultValue=""/>
        <property uiName="volume" asName="volume" defaultValue="0.75"/>
        <property uiName="time" asName="" defaultValue=""/>
        <property uiName="buffer" asName="" defaultValue=""/>

        <!--Should be removed-->
        <property uiName="play" asName="play()" defaultValue=""/>
    </class>
</ClassPaths>

=== aikitpete/uiclientiphone/src/configuration/files/uiproperties.xml
<ClassPaths xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../schemas/classpathfile.xml.xsd">
    <!--TODO schema should be edited-->

    <class name="styles" path="">
        <property uiName="font.size" asName="fontSize" defaultValue="20"/>
        <property uiName="font.color" asName="color" defaultValue="0x4C566C"/>
        <property uiName="font.bold" asName="fontWeight" defaultValue="bold"/>
        <property uiName="font.name" asName="fontName" defaultValue="Helvetica"/>
        <property uiName="font.family" asName="fontFamily" defaultValue="Helvetica"/>
    </class>

    <class name="positions" path="">
        <property uiName="x" asName="" defaultValue=""/>
        <property uiName="y" asName="" defaultValue=""/>
        <property uiName="width" asName="" defaultValue=""/>
        <property uiName="height" asName="" defaultValue=""/>
    </class>

</ClassPaths>
